### ISSUE TITLE
Afficher une erreur explicite quand le runner n'a pas été trouvé

### ISSUE THREAD

**Issue by fuhrmannb** [jocelyndubois/ncg-ud-stream#10]
```
error: [ncg-ud-stream] TypeError: Cannot read property 'forEach' of null
    at Object.func (E:\Stream\nodecg\bundles\ncg-ud-stream\extension\index.js:35:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by fuhrmannb** [comment]
En fait, j'avais mis le mauvais identifiant pour le runner.

Il faudrait un check sur le nom du runner avant de faire les opérations pour avoir une erreur plus explicite.

**Comment by jocelyndubois** [comment]
Je clos, rendu obsolète par l'issue #9
